// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    [YandexResourceType("yandex:index/mdbSqlserverCluster:MdbSqlserverCluster")]
    public partial class MdbSqlserverCluster : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Time to start the daily backup, in the UTC.
        /// </summary>
        [Output("backupWindowStart")]
        public Output<Outputs.MdbSqlserverClusterBackupWindowStart> BackupWindowStart { get; private set; } = null!;

        /// <summary>
        /// The creation timestamp of the resource.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// A database of the SQLServer cluster.
        /// </summary>
        [Output("databases")]
        public Output<ImmutableArray<Outputs.MdbSqlserverClusterDatabase>> Databases { get; private set; } = null!;

        /// <summary>
        /// The `true` value means that resource is protected from accidental deletion.
        /// </summary>
        [Output("deletionProtection")]
        public Output<bool> DeletionProtection { get; private set; } = null!;

        /// <summary>
        /// The resource description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Deployment environment of the SQLServer cluster. (PRODUCTION, PRESTABLE).
        /// </summary>
        [Output("environment")]
        public Output<string> Environment { get; private set; } = null!;

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Output("folderId")]
        public Output<string> FolderId { get; private set; } = null!;

        /// <summary>
        /// Aggregated health of the cluster.
        /// </summary>
        [Output("health")]
        public Output<string> Health { get; private set; } = null!;

        /// <summary>
        /// A list of IDs of the host groups hosting VMs of the cluster.
        /// </summary>
        [Output("hostGroupIds")]
        public Output<ImmutableArray<string>> HostGroupIds { get; private set; } = null!;

        /// <summary>
        /// A host of the SQLServer cluster.
        /// </summary>
        [Output("hosts")]
        public Output<ImmutableArray<Outputs.MdbSqlserverClusterHost>> Hosts { get; private set; } = null!;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// The resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The `VPC Network ID` of subnets which resource attached to.
        /// </summary>
        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;

        /// <summary>
        /// Resources allocated to hosts of the SQLServer cluster.
        /// </summary>
        [Output("resources")]
        public Output<Outputs.MdbSqlserverClusterResources> Resources { get; private set; } = null!;

        /// <summary>
        /// The list of security groups applied to resource or their components.
        /// </summary>
        [Output("securityGroupIds")]
        public Output<ImmutableArray<string>> SecurityGroupIds { get; private set; } = null!;

        /// <summary>
        /// SQL Collation cluster will be created with. This attribute cannot be changed when cluster is created!
        /// </summary>
        [Output("sqlcollation")]
        public Output<string> Sqlcollation { get; private set; } = null!;

        /// <summary>
        /// SQLServer cluster config. Detail info in `SQLServer config` section.
        /// </summary>
        [Output("sqlserverConfig")]
        public Output<ImmutableDictionary<string, string>> SqlserverConfig { get; private set; } = null!;

        /// <summary>
        /// Status of the cluster.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// A user of the SQLServer cluster.
        /// </summary>
        [Output("users")]
        public Output<ImmutableArray<Outputs.MdbSqlserverClusterUser>> Users { get; private set; } = null!;

        /// <summary>
        /// Version of the SQLServer cluster. (2016sp2std, 2016sp2ent).
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a MdbSqlserverCluster resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MdbSqlserverCluster(string name, MdbSqlserverClusterArgs args, CustomResourceOptions? options = null)
            : base("yandex:index/mdbSqlserverCluster:MdbSqlserverCluster", name, args ?? new MdbSqlserverClusterArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MdbSqlserverCluster(string name, Input<string> id, MdbSqlserverClusterState? state = null, CustomResourceOptions? options = null)
            : base("yandex:index/mdbSqlserverCluster:MdbSqlserverCluster", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MdbSqlserverCluster resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MdbSqlserverCluster Get(string name, Input<string> id, MdbSqlserverClusterState? state = null, CustomResourceOptions? options = null)
        {
            return new MdbSqlserverCluster(name, id, state, options);
        }
    }

    public sealed class MdbSqlserverClusterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Time to start the daily backup, in the UTC.
        /// </summary>
        [Input("backupWindowStart")]
        public Input<Inputs.MdbSqlserverClusterBackupWindowStartArgs>? BackupWindowStart { get; set; }

        [Input("databases", required: true)]
        private InputList<Inputs.MdbSqlserverClusterDatabaseArgs>? _databases;

        /// <summary>
        /// A database of the SQLServer cluster.
        /// </summary>
        public InputList<Inputs.MdbSqlserverClusterDatabaseArgs> Databases
        {
            get => _databases ?? (_databases = new InputList<Inputs.MdbSqlserverClusterDatabaseArgs>());
            set => _databases = value;
        }

        /// <summary>
        /// The `true` value means that resource is protected from accidental deletion.
        /// </summary>
        [Input("deletionProtection")]
        public Input<bool>? DeletionProtection { get; set; }

        /// <summary>
        /// The resource description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Deployment environment of the SQLServer cluster. (PRODUCTION, PRESTABLE).
        /// </summary>
        [Input("environment", required: true)]
        public Input<string> Environment { get; set; } = null!;

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        [Input("hostGroupIds")]
        private InputList<string>? _hostGroupIds;

        /// <summary>
        /// A list of IDs of the host groups hosting VMs of the cluster.
        /// </summary>
        public InputList<string> HostGroupIds
        {
            get => _hostGroupIds ?? (_hostGroupIds = new InputList<string>());
            set => _hostGroupIds = value;
        }

        [Input("hosts", required: true)]
        private InputList<Inputs.MdbSqlserverClusterHostArgs>? _hosts;

        /// <summary>
        /// A host of the SQLServer cluster.
        /// </summary>
        public InputList<Inputs.MdbSqlserverClusterHostArgs> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<Inputs.MdbSqlserverClusterHostArgs>());
            set => _hosts = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The `VPC Network ID` of subnets which resource attached to.
        /// </summary>
        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        /// <summary>
        /// Resources allocated to hosts of the SQLServer cluster.
        /// </summary>
        [Input("resources", required: true)]
        public Input<Inputs.MdbSqlserverClusterResourcesArgs> Resources { get; set; } = null!;

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// The list of security groups applied to resource or their components.
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        /// <summary>
        /// SQL Collation cluster will be created with. This attribute cannot be changed when cluster is created!
        /// </summary>
        [Input("sqlcollation")]
        public Input<string>? Sqlcollation { get; set; }

        [Input("sqlserverConfig")]
        private InputMap<string>? _sqlserverConfig;

        /// <summary>
        /// SQLServer cluster config. Detail info in `SQLServer config` section.
        /// </summary>
        public InputMap<string> SqlserverConfig
        {
            get => _sqlserverConfig ?? (_sqlserverConfig = new InputMap<string>());
            set => _sqlserverConfig = value;
        }

        [Input("users", required: true)]
        private InputList<Inputs.MdbSqlserverClusterUserArgs>? _users;

        /// <summary>
        /// A user of the SQLServer cluster.
        /// </summary>
        public InputList<Inputs.MdbSqlserverClusterUserArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbSqlserverClusterUserArgs>());
            set => _users = value;
        }

        /// <summary>
        /// Version of the SQLServer cluster. (2016sp2std, 2016sp2ent).
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        public MdbSqlserverClusterArgs()
        {
        }
        public static new MdbSqlserverClusterArgs Empty => new MdbSqlserverClusterArgs();
    }

    public sealed class MdbSqlserverClusterState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Time to start the daily backup, in the UTC.
        /// </summary>
        [Input("backupWindowStart")]
        public Input<Inputs.MdbSqlserverClusterBackupWindowStartGetArgs>? BackupWindowStart { get; set; }

        /// <summary>
        /// The creation timestamp of the resource.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("databases")]
        private InputList<Inputs.MdbSqlserverClusterDatabaseGetArgs>? _databases;

        /// <summary>
        /// A database of the SQLServer cluster.
        /// </summary>
        public InputList<Inputs.MdbSqlserverClusterDatabaseGetArgs> Databases
        {
            get => _databases ?? (_databases = new InputList<Inputs.MdbSqlserverClusterDatabaseGetArgs>());
            set => _databases = value;
        }

        /// <summary>
        /// The `true` value means that resource is protected from accidental deletion.
        /// </summary>
        [Input("deletionProtection")]
        public Input<bool>? DeletionProtection { get; set; }

        /// <summary>
        /// The resource description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Deployment environment of the SQLServer cluster. (PRODUCTION, PRESTABLE).
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
        /// </summary>
        [Input("folderId")]
        public Input<string>? FolderId { get; set; }

        /// <summary>
        /// Aggregated health of the cluster.
        /// </summary>
        [Input("health")]
        public Input<string>? Health { get; set; }

        [Input("hostGroupIds")]
        private InputList<string>? _hostGroupIds;

        /// <summary>
        /// A list of IDs of the host groups hosting VMs of the cluster.
        /// </summary>
        public InputList<string> HostGroupIds
        {
            get => _hostGroupIds ?? (_hostGroupIds = new InputList<string>());
            set => _hostGroupIds = value;
        }

        [Input("hosts")]
        private InputList<Inputs.MdbSqlserverClusterHostGetArgs>? _hosts;

        /// <summary>
        /// A host of the SQLServer cluster.
        /// </summary>
        public InputList<Inputs.MdbSqlserverClusterHostGetArgs> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<Inputs.MdbSqlserverClusterHostGetArgs>());
            set => _hosts = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// A set of key/value label pairs which assigned to resource.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The `VPC Network ID` of subnets which resource attached to.
        /// </summary>
        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        /// <summary>
        /// Resources allocated to hosts of the SQLServer cluster.
        /// </summary>
        [Input("resources")]
        public Input<Inputs.MdbSqlserverClusterResourcesGetArgs>? Resources { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// The list of security groups applied to resource or their components.
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        /// <summary>
        /// SQL Collation cluster will be created with. This attribute cannot be changed when cluster is created!
        /// </summary>
        [Input("sqlcollation")]
        public Input<string>? Sqlcollation { get; set; }

        [Input("sqlserverConfig")]
        private InputMap<string>? _sqlserverConfig;

        /// <summary>
        /// SQLServer cluster config. Detail info in `SQLServer config` section.
        /// </summary>
        public InputMap<string> SqlserverConfig
        {
            get => _sqlserverConfig ?? (_sqlserverConfig = new InputMap<string>());
            set => _sqlserverConfig = value;
        }

        /// <summary>
        /// Status of the cluster.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("users")]
        private InputList<Inputs.MdbSqlserverClusterUserGetArgs>? _users;

        /// <summary>
        /// A user of the SQLServer cluster.
        /// </summary>
        public InputList<Inputs.MdbSqlserverClusterUserGetArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.MdbSqlserverClusterUserGetArgs>());
            set => _users = value;
        }

        /// <summary>
        /// Version of the SQLServer cluster. (2016sp2std, 2016sp2ent).
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public MdbSqlserverClusterState()
        {
        }
        public static new MdbSqlserverClusterState Empty => new MdbSqlserverClusterState();
    }
}
