// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-yandex/sdk/go/yandex/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetComputeDiskPlacementGroup(ctx *pulumi.Context, args *GetComputeDiskPlacementGroupArgs, opts ...pulumi.InvokeOption) (*GetComputeDiskPlacementGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetComputeDiskPlacementGroupResult
	err := ctx.Invoke("yandex:index/getComputeDiskPlacementGroup:getComputeDiskPlacementGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeDiskPlacementGroup.
type GetComputeDiskPlacementGroupArgs struct {
	Description *string           `pulumi:"description"`
	FolderId    *string           `pulumi:"folderId"`
	GroupId     *string           `pulumi:"groupId"`
	Labels      map[string]string `pulumi:"labels"`
	Name        *string           `pulumi:"name"`
	Zone        *string           `pulumi:"zone"`
}

// A collection of values returned by getComputeDiskPlacementGroup.
type GetComputeDiskPlacementGroupResult struct {
	CreatedAt   string  `pulumi:"createdAt"`
	Description *string `pulumi:"description"`
	FolderId    string  `pulumi:"folderId"`
	GroupId     string  `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id     string            `pulumi:"id"`
	Labels map[string]string `pulumi:"labels"`
	Name   *string           `pulumi:"name"`
	Status string            `pulumi:"status"`
	Zone   *string           `pulumi:"zone"`
}

func GetComputeDiskPlacementGroupOutput(ctx *pulumi.Context, args GetComputeDiskPlacementGroupOutputArgs, opts ...pulumi.InvokeOption) GetComputeDiskPlacementGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetComputeDiskPlacementGroupResultOutput, error) {
			args := v.(GetComputeDiskPlacementGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getComputeDiskPlacementGroup:getComputeDiskPlacementGroup", args, GetComputeDiskPlacementGroupResultOutput{}, options).(GetComputeDiskPlacementGroupResultOutput), nil
		}).(GetComputeDiskPlacementGroupResultOutput)
}

// A collection of arguments for invoking getComputeDiskPlacementGroup.
type GetComputeDiskPlacementGroupOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	FolderId    pulumi.StringPtrInput `pulumi:"folderId"`
	GroupId     pulumi.StringPtrInput `pulumi:"groupId"`
	Labels      pulumi.StringMapInput `pulumi:"labels"`
	Name        pulumi.StringPtrInput `pulumi:"name"`
	Zone        pulumi.StringPtrInput `pulumi:"zone"`
}

func (GetComputeDiskPlacementGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComputeDiskPlacementGroupArgs)(nil)).Elem()
}

// A collection of values returned by getComputeDiskPlacementGroup.
type GetComputeDiskPlacementGroupResultOutput struct{ *pulumi.OutputState }

func (GetComputeDiskPlacementGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetComputeDiskPlacementGroupResult)(nil)).Elem()
}

func (o GetComputeDiskPlacementGroupResultOutput) ToGetComputeDiskPlacementGroupResultOutput() GetComputeDiskPlacementGroupResultOutput {
	return o
}

func (o GetComputeDiskPlacementGroupResultOutput) ToGetComputeDiskPlacementGroupResultOutputWithContext(ctx context.Context) GetComputeDiskPlacementGroupResultOutput {
	return o
}

func (o GetComputeDiskPlacementGroupResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o GetComputeDiskPlacementGroupResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o GetComputeDiskPlacementGroupResultOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) string { return v.FolderId }).(pulumi.StringOutput)
}

func (o GetComputeDiskPlacementGroupResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) string { return v.GroupId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetComputeDiskPlacementGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetComputeDiskPlacementGroupResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o GetComputeDiskPlacementGroupResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o GetComputeDiskPlacementGroupResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetComputeDiskPlacementGroupResultOutput) Zone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetComputeDiskPlacementGroupResult) *string { return v.Zone }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetComputeDiskPlacementGroupResultOutput{})
}
