// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DataprocClusterClusterConfigHadoop
    {
        /// <summary>
        /// List of initialization scripts.
        /// </summary>
        public readonly ImmutableArray<Outputs.DataprocClusterClusterConfigHadoopInitializationAction> InitializationActions;
        /// <summary>
        /// Whether to enable authorization via OS Login.
        /// </summary>
        public readonly bool? Oslogin;
        /// <summary>
        /// A set of key/value pairs that are used to configure cluster services.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Properties;
        /// <summary>
        /// List of services to run on Yandex Data Processing cluster.
        /// </summary>
        public readonly ImmutableArray<string> Services;
        /// <summary>
        /// List of SSH public keys to put to the hosts of the cluster. For information on how to connect to the cluster, see [the official documentation](https://yandex.cloud/docs/data-proc/operations/connect).
        /// </summary>
        public readonly ImmutableArray<string> SshPublicKeys;

        [OutputConstructor]
        private DataprocClusterClusterConfigHadoop(
            ImmutableArray<Outputs.DataprocClusterClusterConfigHadoopInitializationAction> initializationActions,

            bool? oslogin,

            ImmutableDictionary<string, string>? properties,

            ImmutableArray<string> services,

            ImmutableArray<string> sshPublicKeys)
        {
            InitializationActions = initializationActions;
            Oslogin = oslogin;
            Properties = properties;
            Services = services;
            SshPublicKeys = sshPublicKeys;
        }
    }
}
