// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferTransferTransformationTransformerFilterRows
    {
        /// <summary>
        /// Filtering criterion. This can be comparison operators for numeric, string, and Boolean values, comparison to NULL, and checking whether a substring is part of a string. See details [here](https://yandex.cloud/docs/data-transfer/concepts/data-transformation#append-only-sources).
        /// </summary>
        public readonly string? Filter;
        /// <summary>
        /// Table filter.
        /// </summary>
        public readonly Outputs.DatatransferTransferTransformationTransformerFilterRowsTables? Tables;

        [OutputConstructor]
        private DatatransferTransferTransformationTransformerFilterRows(
            string? filter,

            Outputs.DatatransferTransferTransformationTransformerFilterRowsTables? tables)
        {
            Filter = filter;
            Tables = tables;
        }
    }
}
