// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DatatransferEndpointSettingsKafkaSourceConnectionOnPremise
    {
        public readonly ImmutableArray<string> BrokerUrls;
        public readonly string? SubnetId;
        public readonly Outputs.DatatransferEndpointSettingsKafkaSourceConnectionOnPremiseTlsMode? TlsMode;

        [OutputConstructor]
        private DatatransferEndpointSettingsKafkaSourceConnectionOnPremise(
            ImmutableArray<string> brokerUrls,

            string? subnetId,

            Outputs.DatatransferEndpointSettingsKafkaSourceConnectionOnPremiseTlsMode? tlsMode)
        {
            BrokerUrls = brokerUrls;
            SubnetId = subnetId;
            TlsMode = tlsMode;
        }
    }
}
