// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class FunctionTriggerLogging
    {
        /// <summary>
        /// Batch Duration in seconds for Yandex Cloud Functions Trigger.
        /// </summary>
        public readonly string BatchCutoff;
        /// <summary>
        /// Batch Size for Yandex Cloud Functions Trigger.
        /// </summary>
        public readonly string? BatchSize;
        /// <summary>
        /// Logging group ID for Yandex Cloud Functions Trigger.
        /// </summary>
        public readonly string GroupId;
        /// <summary>
        /// Logging level filter setting for Yandex Cloud Functions Trigger.
        /// </summary>
        public readonly ImmutableArray<string> Levels;
        /// <summary>
        /// Resource ID filter setting for Yandex Cloud Functions Trigger.
        /// </summary>
        public readonly ImmutableArray<string> ResourceIds;
        /// <summary>
        /// Resource type filter setting for Yandex Cloud Functions Trigger.
        /// </summary>
        public readonly ImmutableArray<string> ResourceTypes;
        /// <summary>
        /// Logging stream name filter setting for Yandex Cloud Functions Trigger.
        /// </summary>
        public readonly ImmutableArray<string> StreamNames;

        [OutputConstructor]
        private FunctionTriggerLogging(
            string batchCutoff,

            string? batchSize,

            string groupId,

            ImmutableArray<string> levels,

            ImmutableArray<string> resourceIds,

            ImmutableArray<string> resourceTypes,

            ImmutableArray<string> streamNames)
        {
            BatchCutoff = batchCutoff;
            BatchSize = batchSize;
            GroupId = groupId;
            Levels = levels;
            ResourceIds = resourceIds;
            ResourceTypes = resourceTypes;
            StreamNames = streamNames;
        }
    }
}
