// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetAlbLoadBalancerListenerEndpointAddressInternalIpv4AddressResult
    {
        /// <summary>
        /// Provided by the client or computed automatically.
        /// </summary>
        public readonly string Address;
        /// <summary>
        /// ID of the subnet that the address belongs to.
        /// </summary>
        public readonly string SubnetId;

        [OutputConstructor]
        private GetAlbLoadBalancerListenerEndpointAddressInternalIpv4AddressResult(
            string address,

            string subnetId)
        {
            Address = address;
            SubnetId = subnetId;
        }
    }
}
