// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetAlbVirtualHostRouteGrpcRouteResult
    {
        /// <summary>
        /// Checks `/` prefix by default.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlbVirtualHostRouteGrpcRouteGrpcMatchResult> GrpcMatches;
        /// <summary>
        /// gRPC route action resource.
        /// 
        /// &gt; Only one type of host rewrite specifiers `HostRewrite` or `AutoHostRewrite` should be specified.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlbVirtualHostRouteGrpcRouteGrpcRouteActionResult> GrpcRouteActions;
        /// <summary>
        /// gRPC status response action resource.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlbVirtualHostRouteGrpcRouteGrpcStatusResponseActionResult> GrpcStatusResponseActions;

        [OutputConstructor]
        private GetAlbVirtualHostRouteGrpcRouteResult(
            ImmutableArray<Outputs.GetAlbVirtualHostRouteGrpcRouteGrpcMatchResult> grpcMatches,

            ImmutableArray<Outputs.GetAlbVirtualHostRouteGrpcRouteGrpcRouteActionResult> grpcRouteActions,

            ImmutableArray<Outputs.GetAlbVirtualHostRouteGrpcRouteGrpcStatusResponseActionResult> grpcStatusResponseActions)
        {
            GrpcMatches = grpcMatches;
            GrpcRouteActions = grpcRouteActions;
            GrpcStatusResponseActions = grpcStatusResponseActions;
        }
    }
}
