// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetAlbVirtualHostRouteRouteOptionRbacPrincipalAndPrincipalHeaderResult
    {
        public readonly string Name;
        /// <summary>
        /// The `Path` and `Fqmn` blocks.
        /// 
        /// &gt; Exactly one type of string matches `Exact`, `Prefix` or `Regex` should be specified.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAlbVirtualHostRouteRouteOptionRbacPrincipalAndPrincipalHeaderValueResult> Values;

        [OutputConstructor]
        private GetAlbVirtualHostRouteRouteOptionRbacPrincipalAndPrincipalHeaderResult(
            string name,

            ImmutableArray<Outputs.GetAlbVirtualHostRouteRouteOptionRbacPrincipalAndPrincipalHeaderValueResult> values)
        {
            Name = name;
            Values = values;
        }
    }
}
