// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbMongodbClusterClusterConfigMongodResult
    {
        /// <summary>
        /// A set of audit log settings (see the [auditLog](https://www.mongodb.com/docs/manual/reference/configuration-options/#auditlog-options) option). Available only in enterprise edition.
        /// </summary>
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodAuditLogResult AuditLog;
        /// <summary>
        /// A set of network settings (see the [net](https://www.mongodb.com/docs/manual/reference/configuration-options/#net-options) option).
        /// </summary>
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodNetResult? Net;
        /// <summary>
        /// A set of profiling settings (see the [operationProfiling](https://www.mongodb.com/docs/manual/reference/configuration-options/#operationprofiling-options) option).
        /// </summary>
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodOperationProfilingResult? OperationProfiling;
        /// <summary>
        /// A set of MongoDB Security settings (see the [security](https://www.mongodb.com/docs/manual/reference/configuration-options/#security-options) option). Available only in enterprise edition.
        /// </summary>
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodSecurityResult Security;
        /// <summary>
        /// A set of MongoDB Server Parameters (see the [setParameter](https://www.mongodb.com/docs/manual/reference/configuration-options/#setparameter-option) option).
        /// </summary>
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodSetParameterResult SetParameter;
        /// <summary>
        /// A set of storage settings (see the [storage](https://www.mongodb.com/docs/manual/reference/configuration-options/#storage-options) option).
        /// </summary>
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodStorageResult? Storage;

        [OutputConstructor]
        private GetMdbMongodbClusterClusterConfigMongodResult(
            Outputs.GetMdbMongodbClusterClusterConfigMongodAuditLogResult auditLog,

            Outputs.GetMdbMongodbClusterClusterConfigMongodNetResult? net,

            Outputs.GetMdbMongodbClusterClusterConfigMongodOperationProfilingResult? operationProfiling,

            Outputs.GetMdbMongodbClusterClusterConfigMongodSecurityResult security,

            Outputs.GetMdbMongodbClusterClusterConfigMongodSetParameterResult setParameter,

            Outputs.GetMdbMongodbClusterClusterConfigMongodStorageResult? storage)
        {
            AuditLog = auditLog;
            Net = net;
            OperationProfiling = operationProfiling;
            Security = security;
            SetParameter = setParameter;
            Storage = storage;
        }
    }
}
