// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbMongodbClusterClusterConfigMongodSetParameterResult
    {
        /// <summary>
        /// Enables the auditing of authorization successes. Can be either true or false. For more information, see the [auditAuthorizationSuccess](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.auditAuthorizationSuccess) description in the official documentation. Available only in enterprise edition.
        /// </summary>
        public readonly bool? AuditAuthorizationSuccess;
        /// <summary>
        /// Enables the flow control. Can be either true or false. For more information, see the [enableFlowControl](https://www.mongodb.com/docs/rapid/reference/parameters/#mongodb-parameter-param.enableFlowControl) description in the official documentation.
        /// </summary>
        public readonly bool? EnableFlowControl;
        /// <summary>
        /// The target maximum majority committed lag when running with flow control. For more information, see the [flowControlTargetLagSeconds](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.flowControlTargetLagSeconds) description in the official documentation.
        /// </summary>
        public readonly int? FlowControlTargetLagSeconds;
        /// <summary>
        /// The amount of time to wait to log a warning once the flow control mechanism detects the majority commit point has not moved. For more information, see the [flowControlWarnThresholdSeconds](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.flowControlWarnThresholdSeconds) description in the official documentation.
        /// </summary>
        public readonly int? FlowControlWarnThresholdSeconds;
        /// <summary>
        /// Time in milliseconds to wait between batches of insertions during cloning step of the migration process. For more information, see the [migrateCloneInsertionBatchDelayMs](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.migrateCloneInsertionBatchDelayMS) description in the official documentation.
        /// </summary>
        public readonly int? MigrateCloneInsertionBatchDelayMs;
        /// <summary>
        /// The maximum number of documents to insert in a single batch during the cloning step of the migration process. For more information, see the [migrateCloneInsertionBatchSize](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.migrateCloneInsertionBatchSize) description in the official documentation.
        /// </summary>
        public readonly int? MigrateCloneInsertionBatchSize;
        /// <summary>
        /// The minimum time window in seconds for which the storage engine keeps the snapshot history. For more information, see the [minSnapshotHistoryWindowInSeconds](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.minSnapshotHistoryWindowInSeconds) description in the official documentation.
        /// </summary>
        public readonly int? MinSnapshotHistoryWindowInSeconds;
        /// <summary>
        /// A set of MongoDB Mirror Reads settings (see the [mirrorReads](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.mirrorReads) option).
        /// </summary>
        public readonly Outputs.GetMdbMongodbClusterClusterConfigMongodSetParameterMirrorReadsResult? MirrorReads;
        /// <summary>
        /// Minimum delay before a migrated chunk is deleted from the source shard. For more information, see the [orphanCleanupDelaySecs](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.orphanCleanupDelaySecs) description in the official documentation.
        /// </summary>
        public readonly int? OrphanCleanupDelaySecs;
        /// <summary>
        /// Specifies the maximum batch size used for updating the persisted chunk cache. For more information, see the [persistedChunkCacheUpdateMaxBatchSize](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.persistedChunkCacheUpdateMaxBatchSize) description in the official documentation.
        /// </summary>
        public readonly int? PersistedChunkCacheUpdateMaxBatchSize;
        /// <summary>
        /// The amount of time in milliseconds to wait before the next batch of deletion during the cleanup stage of chunk migration (or the cleanupOrphaned command). For more information, see the [rangeDeleterBatchDelayMS](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.rangeDeleterBatchDelayMS) description in the official documentation.
        /// </summary>
        public readonly int? RangeDeleterBatchDelayMs;
        /// <summary>
        /// The maximum number of documents in each batch to delete during the cleanup stage of chunk migration (or the cleanupOrphaned command). For more information, see the [rangeDeleterBatchSize](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.rangeDeleterBatchSize) description in the official documentation.
        /// </summary>
        public readonly int? RangeDeleterBatchSize;

        [OutputConstructor]
        private GetMdbMongodbClusterClusterConfigMongodSetParameterResult(
            bool? auditAuthorizationSuccess,

            bool? enableFlowControl,

            int? flowControlTargetLagSeconds,

            int? flowControlWarnThresholdSeconds,

            int? migrateCloneInsertionBatchDelayMs,

            int? migrateCloneInsertionBatchSize,

            int? minSnapshotHistoryWindowInSeconds,

            Outputs.GetMdbMongodbClusterClusterConfigMongodSetParameterMirrorReadsResult? mirrorReads,

            int? orphanCleanupDelaySecs,

            int? persistedChunkCacheUpdateMaxBatchSize,

            int? rangeDeleterBatchDelayMs,

            int? rangeDeleterBatchSize)
        {
            AuditAuthorizationSuccess = auditAuthorizationSuccess;
            EnableFlowControl = enableFlowControl;
            FlowControlTargetLagSeconds = flowControlTargetLagSeconds;
            FlowControlWarnThresholdSeconds = flowControlWarnThresholdSeconds;
            MigrateCloneInsertionBatchDelayMs = migrateCloneInsertionBatchDelayMs;
            MigrateCloneInsertionBatchSize = migrateCloneInsertionBatchSize;
            MinSnapshotHistoryWindowInSeconds = minSnapshotHistoryWindowInSeconds;
            MirrorReads = mirrorReads;
            OrphanCleanupDelaySecs = orphanCleanupDelaySecs;
            PersistedChunkCacheUpdateMaxBatchSize = persistedChunkCacheUpdateMaxBatchSize;
            RangeDeleterBatchDelayMs = rangeDeleterBatchDelayMs;
            RangeDeleterBatchSize = rangeDeleterBatchSize;
        }
    }
}
