// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbGreenplumClusterBackgroundActivityResult
    {
        public readonly ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityAnalyzeAndVacuumResult> AnalyzeAndVacuums;
        public readonly ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleInTransactionResult> QueryKillerIdleInTransactions;
        public readonly ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleResult> QueryKillerIdles;
        public readonly ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerLongRunningResult> QueryKillerLongRunnings;

        [OutputConstructor]
        private GetMdbGreenplumClusterBackgroundActivityResult(
            ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityAnalyzeAndVacuumResult> analyzeAndVacuums,

            ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleInTransactionResult> queryKillerIdleInTransactions,

            ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerIdleResult> queryKillerIdles,

            ImmutableArray<Outputs.GetMdbGreenplumClusterBackgroundActivityQueryKillerLongRunningResult> queryKillerLongRunnings)
        {
            AnalyzeAndVacuums = analyzeAndVacuums;
            QueryKillerIdleInTransactions = queryKillerIdleInTransactions;
            QueryKillerIdles = queryKillerIdles;
            QueryKillerLongRunnings = queryKillerLongRunnings;
        }
    }
}
