// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbClickhouseClusterClickhouseConfigJdbcBridgeResult
    {
        /// <summary>
        /// Host of jdbc bridge.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// Port of jdbc bridge. Default value: 9019.
        /// </summary>
        public readonly int Port;

        [OutputConstructor]
        private GetMdbClickhouseClusterClickhouseConfigJdbcBridgeResult(
            string? host,

            int port)
        {
            Host = host;
            Port = port;
        }
    }
}
