// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetSwsWafProfileRuleSetMlRuleSetRuleGroupResult
    {
        public readonly string Action;
        public readonly string Id;
        public readonly int InboundAnomalyScore;
        public readonly bool IsEnabled;

        [OutputConstructor]
        private GetSwsWafProfileRuleSetMlRuleSetRuleGroupResult(
            string action,

            string id,

            int inboundAnomalyScore,

            bool isEnabled)
        {
            Action = action;
            Id = id;
            InboundAnomalyScore = inboundAnomalyScore;
            IsEnabled = isEnabled;
        }
    }
}
