// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MdbClickhouseClusterClickhouseConfigKafkaTopic
    {
        /// <summary>
        /// Kafka topic name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Kafka connection settings.
        /// </summary>
        public readonly Outputs.MdbClickhouseClusterClickhouseConfigKafkaTopicSettings? Settings;

        [OutputConstructor]
        private MdbClickhouseClusterClickhouseConfigKafkaTopic(
            string name,

            Outputs.MdbClickhouseClusterClickhouseConfigKafkaTopicSettings? settings)
        {
            Name = name;
            Settings = settings;
        }
    }
}
