// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MdbKafkaClusterConfigKafka
    {
        /// <summary>
        /// User-defined settings for the Kafka cluster. For more information, see [the official documentation](https://yandex.cloud/docs/managed-kafka/operations/cluster-update) and [the Kafka documentation](https://kafka.apache.org/documentation/#configuration).
        /// </summary>
        public readonly Outputs.MdbKafkaClusterConfigKafkaKafkaConfig? KafkaConfig;
        /// <summary>
        /// Resources allocated to hosts of the Kafka subcluster.
        /// </summary>
        public readonly Outputs.MdbKafkaClusterConfigKafkaResources Resources;

        [OutputConstructor]
        private MdbKafkaClusterConfigKafka(
            Outputs.MdbKafkaClusterConfigKafkaKafkaConfig? kafkaConfig,

            Outputs.MdbKafkaClusterConfigKafkaResources resources)
        {
            KafkaConfig = kafkaConfig;
            Resources = resources;
        }
    }
}
