// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MdbRedisClusterAccess
    {
        /// <summary>
        /// Allow access for DataLens. Can be either `True` or `False`.
        /// </summary>
        public readonly bool? DataLens;
        /// <summary>
        /// Allow access for Web SQL. Can be either `True` or `False`.
        /// </summary>
        public readonly bool? WebSql;

        [OutputConstructor]
        private MdbRedisClusterAccess(
            bool? dataLens,

            bool? webSql)
        {
            DataLens = dataLens;
            WebSql = webSql;
        }
    }
}
