// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MonitoringDashboardParametrization
    {
        /// <summary>
        /// Dashboard parameters.
        /// </summary>
        public readonly ImmutableArray<Outputs.MonitoringDashboardParametrizationParameter> Parameters;
        /// <summary>
        /// Dashboard predefined parameters selector.
        /// </summary>
        public readonly string? Selectors;

        [OutputConstructor]
        private MonitoringDashboardParametrization(
            ImmutableArray<Outputs.MonitoringDashboardParametrizationParameter> parameters,

            string? selectors)
        {
            Parameters = parameters;
            Selectors = selectors;
        }
    }
}
