// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MonitoringDashboardWidgetChartQuery
    {
        /// <summary>
        /// Downsampling settings
        /// </summary>
        public readonly ImmutableArray<Outputs.MonitoringDashboardWidgetChartQueryDownsampling> Downsamplings;
        /// <summary>
        /// Downsampling settings
        /// </summary>
        public readonly ImmutableArray<Outputs.MonitoringDashboardWidgetChartQueryTarget> Targets;

        [OutputConstructor]
        private MonitoringDashboardWidgetChartQuery(
            ImmutableArray<Outputs.MonitoringDashboardWidgetChartQueryDownsampling> downsamplings,

            ImmutableArray<Outputs.MonitoringDashboardWidgetChartQueryTarget> targets)
        {
            Downsamplings = downsamplings;
            Targets = targets;
        }
    }
}
