// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class MonitoringDashboardWidgetChartVisualizationSetting
    {
        /// <summary>
        /// Aggregation
        /// </summary>
        public readonly string? Aggregation;
        /// <summary>
        /// Color scheme settings
        /// </summary>
        public readonly ImmutableArray<Outputs.MonitoringDashboardWidgetChartVisualizationSettingColorSchemeSetting> ColorSchemeSettings;
        /// <summary>
        /// Heatmap settings
        /// </summary>
        public readonly ImmutableArray<Outputs.MonitoringDashboardWidgetChartVisualizationSettingHeatmapSetting> HeatmapSettings;
        /// <summary>
        /// Interpolate
        /// </summary>
        public readonly string? Interpolate;
        /// <summary>
        /// Normalize
        /// </summary>
        public readonly bool? Normalize;
        /// <summary>
        /// Show chart labels
        /// </summary>
        public readonly bool? ShowLabels;
        /// <summary>
        /// Inside chart title
        /// </summary>
        public readonly string? Title;
        /// <summary>
        /// Visualization type
        /// </summary>
        public readonly string? Type;
        /// <summary>
        /// Y axis settings
        /// </summary>
        public readonly ImmutableArray<Outputs.MonitoringDashboardWidgetChartVisualizationSettingYaxisSetting> YaxisSettings;

        [OutputConstructor]
        private MonitoringDashboardWidgetChartVisualizationSetting(
            string? aggregation,

            ImmutableArray<Outputs.MonitoringDashboardWidgetChartVisualizationSettingColorSchemeSetting> colorSchemeSettings,

            ImmutableArray<Outputs.MonitoringDashboardWidgetChartVisualizationSettingHeatmapSetting> heatmapSettings,

            string? interpolate,

            bool? normalize,

            bool? showLabels,

            string? title,

            string? type,

            ImmutableArray<Outputs.MonitoringDashboardWidgetChartVisualizationSettingYaxisSetting> yaxisSettings)
        {
            Aggregation = aggregation;
            ColorSchemeSettings = colorSchemeSettings;
            HeatmapSettings = heatmapSettings;
            Interpolate = interpolate;
            Normalize = normalize;
            ShowLabels = showLabels;
            Title = title;
            Type = type;
            YaxisSettings = yaxisSettings;
        }
    }
}
