// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuota
    {
        /// <summary>
        /// Action in case of exceeding this quota. Possible values: `DENY`.
        /// </summary>
        public readonly string? Action;
        /// <summary>
        /// The condition for matching the rule. You can find all possibilities of condition in [gRPC specs](https://github.com/yandex-cloud/cloudapi/blob/master/yandex/cloud/smartwebsecurity/v1/security_profile.proto).
        /// </summary>
        public readonly Outputs.SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuotaCondition? Condition;
        /// <summary>
        /// Desired maximum number of requests per period.
        /// </summary>
        public readonly int? Limit;
        /// <summary>
        /// Period of time in seconds.
        /// </summary>
        public readonly int? Period;

        [OutputConstructor]
        private SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuota(
            string? action,

            Outputs.SwsAdvancedRateLimiterProfileAdvancedRateLimiterRuleStaticQuotaCondition? condition,

            int? limit,

            int? period)
        {
            Action = action;
            Condition = condition;
            Limit = limit;
            Period = period;
        }
    }
}
