// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class SwsSecurityProfileSecurityRuleSmartProtection
    {
        /// <summary>
        /// The condition for matching the rule. You can find all possibilities of condition in [gRPC specs](https://github.com/yandex-cloud/cloudapi/blob/master/yandex/cloud/smartwebsecurity/v1/security_profile.proto).
        /// </summary>
        public readonly Outputs.SwsSecurityProfileSecurityRuleSmartProtectionCondition? Condition;
        /// <summary>
        /// Mode of protection. Possible values: `FULL` (full protection means that the traffic will be checked based on ML models and behavioral analysis, with suspicious requests being sent to SmartCaptcha) or `API` (API protection means checking the traffic based on ML models and behavioral analysis without sending suspicious requests to SmartCaptcha. The suspicious requests will be blocked).
        /// </summary>
        public readonly string? Mode;

        [OutputConstructor]
        private SwsSecurityProfileSecurityRuleSmartProtection(
            Outputs.SwsSecurityProfileSecurityRuleSmartProtectionCondition? condition,

            string? mode)
        {
            Condition = condition;
            Mode = mode;
        }
    }
}
