// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class VpcDefaultSecurityGroupEgress
    {
        /// <summary>
        /// Description of the rule.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Minimum port number.
        /// </summary>
        public readonly int? FromPort;
        /// <summary>
        /// The resource identifier.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Labels to assign to this rule.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Labels;
        /// <summary>
        /// Port number (if applied to a single port).
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// Special-purpose targets. `self_security_group` refers to this particular security group. `loadbalancer_healthchecks` represents [loadbalancer health check nodes](https://yandex.cloud/docs/network-load-balancer/concepts/health-check).
        /// </summary>
        public readonly string? PredefinedTarget;
        /// <summary>
        /// One of `ANY`, `TCP`, `UDP`, `ICMP`, `IPV6_ICMP`.
        /// </summary>
        public readonly string Protocol;
        /// <summary>
        /// Target security group ID for this rule.
        /// </summary>
        public readonly string? SecurityGroupId;
        /// <summary>
        /// Maximum port number.
        /// </summary>
        public readonly int? ToPort;
        /// <summary>
        /// The blocks of IPv4 addresses for this rule.
        /// </summary>
        public readonly ImmutableArray<string> V4CidrBlocks;
        /// <summary>
        /// The blocks of IPv6 addresses for this rule. `v6_cidr_blocks` argument is currently not supported. It will be available in the future.
        /// </summary>
        public readonly ImmutableArray<string> V6CidrBlocks;

        [OutputConstructor]
        private VpcDefaultSecurityGroupEgress(
            string? description,

            int? fromPort,

            string? id,

            ImmutableDictionary<string, string>? labels,

            int? port,

            string? predefinedTarget,

            string protocol,

            string? securityGroupId,

            int? toPort,

            ImmutableArray<string> v4CidrBlocks,

            ImmutableArray<string> v6CidrBlocks)
        {
            Description = description;
            FromPort = fromPort;
            Id = id;
            Labels = labels;
            Port = port;
            PredefinedTarget = predefinedTarget;
            Protocol = protocol;
            SecurityGroupId = securityGroupId;
            ToPort = toPort;
            V4CidrBlocks = v4CidrBlocks;
            V6CidrBlocks = v6CidrBlocks;
        }
    }
}
