// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class AlbLoadBalancerAutoScalePolicyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Upper limit for total instance count (across all zones)
        /// </summary>
        [Input("maxSize")]
        public Input<int>? MaxSize { get; set; }

        /// <summary>
        /// Lower limit for instance count in each zone.
        /// </summary>
        [Input("minZoneSize")]
        public Input<int>? MinZoneSize { get; set; }

        public AlbLoadBalancerAutoScalePolicyGetArgs()
        {
        }
        public static new AlbLoadBalancerAutoScalePolicyGetArgs Empty => new AlbLoadBalancerAutoScalePolicyGetArgs();
    }
}
