// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class ComputeImageHardwareGenerationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A newer hardware generation, which always uses `PCI_TOPOLOGY_V2` and UEFI boot.
        /// </summary>
        [Input("generation2Features")]
        public Input<Inputs.ComputeImageHardwareGenerationGeneration2FeaturesGetArgs>? Generation2Features { get; set; }

        /// <summary>
        /// Defines the first known hardware generation and its features.
        /// </summary>
        [Input("legacyFeatures")]
        public Input<Inputs.ComputeImageHardwareGenerationLegacyFeaturesGetArgs>? LegacyFeatures { get; set; }

        public ComputeImageHardwareGenerationGetArgs()
        {
        }
        public static new ComputeImageHardwareGenerationGetArgs Empty => new ComputeImageHardwareGenerationGetArgs();
    }
}
