// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class ComputeImageHardwareGenerationGeneration2FeaturesArgs : global::Pulumi.ResourceArgs
    {
        public ComputeImageHardwareGenerationGeneration2FeaturesArgs()
        {
        }
        public static new ComputeImageHardwareGenerationGeneration2FeaturesArgs Empty => new ComputeImageHardwareGenerationGeneration2FeaturesArgs();
    }
}
