// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class DatatransferEndpointSettingsKafkaTargetConnectionOnPremiseTlsModeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("disabled")]
        public Input<Inputs.DatatransferEndpointSettingsKafkaTargetConnectionOnPremiseTlsModeDisabledGetArgs>? Disabled { get; set; }

        [Input("enabled")]
        public Input<Inputs.DatatransferEndpointSettingsKafkaTargetConnectionOnPremiseTlsModeEnabledGetArgs>? Enabled { get; set; }

        public DatatransferEndpointSettingsKafkaTargetConnectionOnPremiseTlsModeGetArgs()
        {
        }
        public static new DatatransferEndpointSettingsKafkaTargetConnectionOnPremiseTlsModeGetArgs Empty => new DatatransferEndpointSettingsKafkaTargetConnectionOnPremiseTlsModeGetArgs();
    }
}
