// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class DataprocClusterClusterConfigSubclusterSpecGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If `true` then assign public IP addresses to the hosts of the subclusters.
        /// </summary>
        [Input("assignPublicIp")]
        public Input<bool>? AssignPublicIp { get; set; }

        /// <summary>
        /// Autoscaling configuration for compute subclusters.
        /// </summary>
        [Input("autoscalingConfig")]
        public Input<Inputs.DataprocClusterClusterConfigSubclusterSpecAutoscalingConfigGetArgs>? AutoscalingConfig { get; set; }

        /// <summary>
        /// Number of hosts within Yandex Data Processing subcluster.
        /// </summary>
        [Input("hostsCount", required: true)]
        public Input<int> HostsCount { get; set; } = null!;

        /// <summary>
        /// ID of the subcluster.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Name of the Yandex Data Processing subcluster.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Resources allocated to each host of the Yandex Data Processing subcluster.
        /// </summary>
        [Input("resources", required: true)]
        public Input<Inputs.DataprocClusterClusterConfigSubclusterSpecResourcesGetArgs> Resources { get; set; } = null!;

        /// <summary>
        /// Role of the subcluster in the Yandex Data Processing cluster.
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        /// <summary>
        /// The ID of the subnet, to which hosts of the subcluster belong. Subnets of all the subclusters must belong to the same VPC network.
        /// </summary>
        [Input("subnetId", required: true)]
        public Input<string> SubnetId { get; set; } = null!;

        public DataprocClusterClusterConfigSubclusterSpecGetArgs()
        {
        }
        public static new DataprocClusterClusterConfigSubclusterSpecGetArgs Empty => new DataprocClusterClusterConfigSubclusterSpecGetArgs();
    }
}
