// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbKafkaClusterConfigKraftArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Resources allocated to hosts of the KRaft-controller subcluster.
        /// </summary>
        [Input("resources", required: true)]
        public Inputs.GetMdbKafkaClusterConfigKraftResourcesArgs Resources { get; set; } = null!;

        public GetMdbKafkaClusterConfigKraftArgs()
        {
        }
        public static new GetMdbKafkaClusterConfigKraftArgs Empty => new GetMdbKafkaClusterConfigKraftArgs();
    }
}
