// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbKafkaClusterConfigZookeeperResourcesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Volume of the storage available to a ZooKeeper host, in gigabytes.
        /// </summary>
        [Input("diskSize", required: true)]
        public int DiskSize { get; set; }

        /// <summary>
        /// Type of the storage of ZooKeeper hosts. For more information see [the official documentation](https://yandex.cloud/docs/managed-kafka/concepts/storage).
        /// </summary>
        [Input("diskTypeId", required: true)]
        public string DiskTypeId { get; set; } = null!;

        /// <summary>
        /// The ID of the preset for computational resources available to a ZooKeeper host (CPU, memory etc.). For more information, see [the official documentation](https://yandex.cloud/docs/managed-kafka/concepts).
        /// </summary>
        [Input("resourcePresetId", required: true)]
        public string ResourcePresetId { get; set; } = null!;

        public GetMdbKafkaClusterConfigZookeeperResourcesArgs()
        {
        }
        public static new GetMdbKafkaClusterConfigZookeeperResourcesArgs Empty => new GetMdbKafkaClusterConfigZookeeperResourcesArgs();
    }
}
