// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbKafkaClusterConfigInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access policy to the Kafka cluster.
        /// </summary>
        [Input("access", required: true)]
        public Input<Inputs.GetMdbKafkaClusterConfigAccessInputArgs> Access { get; set; } = null!;

        /// <summary>
        /// Determines whether each broker will be assigned a public IP address. The default is `false`.
        /// </summary>
        [Input("assignPublicIp")]
        public Input<bool>? AssignPublicIp { get; set; }

        /// <summary>
        /// Count of brokers per availability zone. The default is `1`.
        /// </summary>
        [Input("brokersCount")]
        public Input<int>? BrokersCount { get; set; }

        /// <summary>
        /// Disk autoscaling settings of the Kafka cluster.
        /// </summary>
        [Input("diskSizeAutoscaling", required: true)]
        public Input<Inputs.GetMdbKafkaClusterConfigDiskSizeAutoscalingInputArgs> DiskSizeAutoscaling { get; set; } = null!;

        /// <summary>
        /// Configuration of the Kafka subcluster.
        /// </summary>
        [Input("kafka", required: true)]
        public Input<Inputs.GetMdbKafkaClusterConfigKafkaInputArgs> Kafka { get; set; } = null!;

        /// <summary>
        /// Configuration of the KRaft-controller subcluster.
        /// </summary>
        [Input("kraft", required: true)]
        public Input<Inputs.GetMdbKafkaClusterConfigKraftInputArgs> Kraft { get; set; } = null!;

        /// <summary>
        /// REST API settings of the Kafka cluster.
        /// </summary>
        [Input("restApi", required: true)]
        public Input<Inputs.GetMdbKafkaClusterConfigRestApiInputArgs> RestApi { get; set; } = null!;

        /// <summary>
        /// Enables managed schema registry on cluster. The default is `false`.
        /// </summary>
        [Input("schemaRegistry")]
        public Input<bool>? SchemaRegistry { get; set; }

        [Input("unmanagedTopics")]
        public Input<bool>? UnmanagedTopics { get; set; }

        /// <summary>
        /// Version of the Kafka server software.
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        [Input("zones", required: true)]
        private InputList<string>? _zones;

        /// <summary>
        /// List of availability zones.
        /// </summary>
        public InputList<string> Zones
        {
            get => _zones ?? (_zones = new InputList<string>());
            set => _zones = value;
        }

        /// <summary>
        /// Configuration of the ZooKeeper subcluster.
        /// </summary>
        [Input("zookeeper", required: true)]
        public Input<Inputs.GetMdbKafkaClusterConfigZookeeperInputArgs> Zookeeper { get; set; } = null!;

        public GetMdbKafkaClusterConfigInputArgs()
        {
        }
        public static new GetMdbKafkaClusterConfigInputArgs Empty => new GetMdbKafkaClusterConfigInputArgs();
    }
}
