// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetServerlessContainerMountInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("ephemeralDisk")]
        public Input<Inputs.GetServerlessContainerMountEphemeralDiskInputArgs>? EphemeralDisk { get; set; }

        [Input("mode", required: true)]
        public Input<string> Mode { get; set; } = null!;

        [Input("mountPointPath", required: true)]
        public Input<string> MountPointPath { get; set; } = null!;

        [Input("objectStorage")]
        public Input<Inputs.GetServerlessContainerMountObjectStorageInputArgs>? ObjectStorage { get; set; }

        public GetServerlessContainerMountInputArgs()
        {
        }
        public static new GetServerlessContainerMountInputArgs Empty => new GetServerlessContainerMountInputArgs();
    }
}
