// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class KubernetesNodeGroupMaintenancePolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Flag that specifies if node group can be repaired automatically. When omitted, default value is `True`.
        /// </summary>
        [Input("autoRepair", required: true)]
        public Input<bool> AutoRepair { get; set; } = null!;

        /// <summary>
        /// Flag specifies if node group can be upgraded automatically. When omitted, default value is `True`.
        /// </summary>
        [Input("autoUpgrade", required: true)]
        public Input<bool> AutoUpgrade { get; set; } = null!;

        [Input("maintenanceWindows")]
        private InputList<Inputs.KubernetesNodeGroupMaintenancePolicyMaintenanceWindowArgs>? _maintenanceWindows;

        /// <summary>
        /// Set of day intervals, when maintenance is allowed for this node group. When omitted, it defaults to any time.
        /// 
        /// To specify time of day interval, for all days, one element should be provided, with two fields set, `StartTime` and `Duration`.
        /// 
        /// To allow maintenance only on specific days of week, please provide list of elements, with all fields set. Only one time interval is allowed for each day of week. Please see `MyNodeGroup` config example.
        /// </summary>
        public InputList<Inputs.KubernetesNodeGroupMaintenancePolicyMaintenanceWindowArgs> MaintenanceWindows
        {
            get => _maintenanceWindows ?? (_maintenanceWindows = new InputList<Inputs.KubernetesNodeGroupMaintenancePolicyMaintenanceWindowArgs>());
            set => _maintenanceWindows = value;
        }

        public KubernetesNodeGroupMaintenancePolicyArgs()
        {
        }
        public static new KubernetesNodeGroupMaintenancePolicyArgs Empty => new KubernetesNodeGroupMaintenancePolicyArgs();
    }
}
