// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbMongodbClusterClusterConfigAccessGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allow access for [Yandex DataLens](https://yandex.cloud/services/datalens).
        /// </summary>
        [Input("dataLens")]
        public Input<bool>? DataLens { get; set; }

        /// <summary>
        /// Allow access for [DataTransfer](https://yandex.cloud/services/data-transfer).
        /// </summary>
        [Input("dataTransfer")]
        public Input<bool>? DataTransfer { get; set; }

        /// <summary>
        /// Allow access for [WebSQL](https://yandex.cloud/ru/docs/websql/).
        /// </summary>
        [Input("webSql")]
        public Input<bool>? WebSql { get; set; }

        public MdbMongodbClusterClusterConfigAccessGetArgs()
        {
        }
        public static new MdbMongodbClusterClusterConfigAccessGetArgs Empty => new MdbMongodbClusterClusterConfigAccessGetArgs();
    }
}
