// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbMongodbClusterClusterConfigMongocfgOplogGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The maximum size of the oplog, as a percentage of the total storage size. For more information, see the [oplog.oplogSizeMB](https://www.mongodb.com/docs/manual/reference/configuration-options/#mongodb-setting-replication.oplogSizeMB) description in the official documentation.
        /// </summary>
        [Input("maxSizePercent")]
        public Input<int>? MaxSizePercent { get; set; }

        /// <summary>
        /// The minimum number of hours to preserve an oplog entry, where decimal values represent the fractions of an hour. For more information, see the [oplog.minRetentionHours](https://www.mongodb.com/docs/manual/reference/configuration-options/#mongodb-setting-replication.oplogSizeMB) description in the official documentation.
        /// </summary>
        [Input("minRetentionHours")]
        public Input<double>? MinRetentionHours { get; set; }

        public MdbMongodbClusterClusterConfigMongocfgOplogGetArgs()
        {
        }
        public static new MdbMongodbClusterClusterConfigMongocfgOplogGetArgs Empty => new MdbMongodbClusterClusterConfigMongocfgOplogGetArgs();
    }
}
