// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class ServerlessEventrouterConnectorYmqGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Batch size for polling
        /// </summary>
        [Input("batchSize")]
        public Input<int>? BatchSize { get; set; }

        /// <summary>
        /// Queue polling timeout
        /// </summary>
        [Input("pollingTimeout")]
        public Input<string>? PollingTimeout { get; set; }

        /// <summary>
        /// Queue ARN. Example: yrn:yc:ymq:ru-central1:aoe***:test
        /// </summary>
        [Input("queueArn", required: true)]
        public Input<string> QueueArn { get; set; } = null!;

        /// <summary>
        /// Service account which has read access to the queue
        /// </summary>
        [Input("serviceAccountId", required: true)]
        public Input<string> ServiceAccountId { get; set; } = null!;

        /// <summary>
        /// Queue visibility timeout override
        /// </summary>
        [Input("visibilityTimeout")]
        public Input<string>? VisibilityTimeout { get; set; }

        public ServerlessEventrouterConnectorYmqGetArgs()
        {
        }
        public static new ServerlessEventrouterConnectorYmqGetArgs Empty => new ServerlessEventrouterConnectorYmqGetArgs();
    }
}
