// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class ServerlessContainerMountEphemeralDiskArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Block size of the ephemeral disk in KB.
        /// </summary>
        [Input("blockSizeKb")]
        public Input<int>? BlockSizeKb { get; set; }

        /// <summary>
        /// Size of the ephemeral disk in GB.
        /// </summary>
        [Input("sizeGb", required: true)]
        public Input<int> SizeGb { get; set; } = null!;

        public ServerlessContainerMountEphemeralDiskArgs()
        {
        }
        public static new ServerlessContainerMountEphemeralDiskArgs Empty => new ServerlessContainerMountEphemeralDiskArgs();
    }
}
