// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class SwsWafProfileRuleSetYaRuleSetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ruleGroups")]
        private InputList<Inputs.SwsWafProfileRuleSetYaRuleSetRuleGroupArgs>? _ruleGroups;

        /// <summary>
        /// List of rule groups.
        /// </summary>
        public InputList<Inputs.SwsWafProfileRuleSetYaRuleSetRuleGroupArgs> RuleGroups
        {
            get => _ruleGroups ?? (_ruleGroups = new InputList<Inputs.SwsWafProfileRuleSetYaRuleSetRuleGroupArgs>());
            set => _ruleGroups = value;
        }

        /// <summary>
        /// Rule set of the Yandex rule set.
        /// </summary>
        [Input("ruleSet", required: true)]
        public Input<Inputs.SwsWafProfileRuleSetYaRuleSetRuleSetArgs> RuleSet { get; set; } = null!;

        public SwsWafProfileRuleSetYaRuleSetArgs()
        {
        }
        public static new SwsWafProfileRuleSetYaRuleSetArgs Empty => new SwsWafProfileRuleSetYaRuleSetArgs();
    }
}
