// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class YdbTopicAutoPartitioningSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The auto partitioning strategy to use
        /// </summary>
        [Input("autoPartitioningStrategy")]
        public Input<string>? AutoPartitioningStrategy { get; set; }

        [Input("autoPartitioningWriteSpeedStrategy")]
        public Input<Inputs.YdbTopicAutoPartitioningSettingsAutoPartitioningWriteSpeedStrategyArgs>? AutoPartitioningWriteSpeedStrategy { get; set; }

        public YdbTopicAutoPartitioningSettingsArgs()
        {
        }
        public static new YdbTopicAutoPartitioningSettingsArgs Empty => new YdbTopicAutoPartitioningSettingsArgs();
    }
}
