// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getServerlessEventrouterConnector(args?: GetServerlessEventrouterConnectorArgs, opts?: pulumi.InvokeOptions): Promise<GetServerlessEventrouterConnectorResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("yandex:index/getServerlessEventrouterConnector:getServerlessEventrouterConnector", {
        "connectorId": args.connectorId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getServerlessEventrouterConnector.
 */
export interface GetServerlessEventrouterConnectorArgs {
    connectorId?: string;
    name?: string;
}

/**
 * A collection of values returned by getServerlessEventrouterConnector.
 */
export interface GetServerlessEventrouterConnectorResult {
    readonly busId: string;
    readonly cloudId: string;
    readonly connectorId?: string;
    readonly createdAt: string;
    readonly deletionProtection: boolean;
    readonly description: string;
    readonly folderId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly name?: string;
    readonly yds: outputs.GetServerlessEventrouterConnectorYd[];
    readonly ymqs: outputs.GetServerlessEventrouterConnectorYmq[];
}
export function getServerlessEventrouterConnectorOutput(args?: GetServerlessEventrouterConnectorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerlessEventrouterConnectorResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("yandex:index/getServerlessEventrouterConnector:getServerlessEventrouterConnector", {
        "connectorId": args.connectorId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getServerlessEventrouterConnector.
 */
export interface GetServerlessEventrouterConnectorOutputArgs {
    connectorId?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
