// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class MdbKafkaTopic extends pulumi.CustomResource {
    /**
     * Get an existing MdbKafkaTopic resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MdbKafkaTopicState, opts?: pulumi.CustomResourceOptions): MdbKafkaTopic {
        return new MdbKafkaTopic(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/mdbKafkaTopic:MdbKafkaTopic';

    /**
     * Returns true if the given object is an instance of MdbKafkaTopic.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MdbKafkaTopic {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MdbKafkaTopic.__pulumiType;
    }

    /**
     * The ID of the Kafka cluster.
     */
    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * The resource name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The number of the topic's partitions.
     */
    declare public readonly partitions: pulumi.Output<number>;
    /**
     * Amount of data copies (replicas) for the topic in the cluster.
     */
    declare public readonly replicationFactor: pulumi.Output<number>;
    /**
     * User-defined settings for the topic. For more information, see [the official documentation](https://yandex.cloud/docs/managed-kafka/concepts/settings-list#topic-settings) and [the Kafka documentation](https://kafka.apache.org/documentation/#topicconfigs).
     */
    declare public readonly topicConfig: pulumi.Output<outputs.MdbKafkaTopicTopicConfig | undefined>;

    /**
     * Create a MdbKafkaTopic resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MdbKafkaTopicArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MdbKafkaTopicArgs | MdbKafkaTopicState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MdbKafkaTopicState | undefined;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["name"] = state?.name;
            resourceInputs["partitions"] = state?.partitions;
            resourceInputs["replicationFactor"] = state?.replicationFactor;
            resourceInputs["topicConfig"] = state?.topicConfig;
        } else {
            const args = argsOrState as MdbKafkaTopicArgs | undefined;
            if (args?.clusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if (args?.partitions === undefined && !opts.urn) {
                throw new Error("Missing required property 'partitions'");
            }
            if (args?.replicationFactor === undefined && !opts.urn) {
                throw new Error("Missing required property 'replicationFactor'");
            }
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["name"] = args?.name;
            resourceInputs["partitions"] = args?.partitions;
            resourceInputs["replicationFactor"] = args?.replicationFactor;
            resourceInputs["topicConfig"] = args?.topicConfig;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MdbKafkaTopic.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MdbKafkaTopic resources.
 */
export interface MdbKafkaTopicState {
    /**
     * The ID of the Kafka cluster.
     */
    clusterId?: pulumi.Input<string>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The number of the topic's partitions.
     */
    partitions?: pulumi.Input<number>;
    /**
     * Amount of data copies (replicas) for the topic in the cluster.
     */
    replicationFactor?: pulumi.Input<number>;
    /**
     * User-defined settings for the topic. For more information, see [the official documentation](https://yandex.cloud/docs/managed-kafka/concepts/settings-list#topic-settings) and [the Kafka documentation](https://kafka.apache.org/documentation/#topicconfigs).
     */
    topicConfig?: pulumi.Input<inputs.MdbKafkaTopicTopicConfig>;
}

/**
 * The set of arguments for constructing a MdbKafkaTopic resource.
 */
export interface MdbKafkaTopicArgs {
    /**
     * The ID of the Kafka cluster.
     */
    clusterId: pulumi.Input<string>;
    /**
     * The resource name.
     */
    name?: pulumi.Input<string>;
    /**
     * The number of the topic's partitions.
     */
    partitions: pulumi.Input<number>;
    /**
     * Amount of data copies (replicas) for the topic in the cluster.
     */
    replicationFactor: pulumi.Input<number>;
    /**
     * User-defined settings for the topic. For more information, see [the official documentation](https://yandex.cloud/docs/managed-kafka/concepts/settings-list#topic-settings) and [the Kafka documentation](https://kafka.apache.org/documentation/#topicconfigs).
     */
    topicConfig?: pulumi.Input<inputs.MdbKafkaTopicTopicConfig>;
}
